name: Build packages

on: workflow_dispatch

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          #- aarch64_cortex-a53
          #- aarch64_cortex-a72
          #- aarch64_generic
          #- i386_pentium-mmx
          #- i386_pentium4
          - x86_64
        sdk:
          #- openwrt-22.03
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get node-empty
        run: |
          git clone https://github.com/sbwml/node-empty

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.21
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-daed-next
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
